version: '3'
services:
  www:
    container_name: 151--testy44

    volumes:
      - /opt/app/:/opt/app/
    ports:
      - "80:80"
    build:
      context: .

  rethinkdb:
    image: rethinkdb
    volumes:
      - /opt/app/db/:/opt/app/db/
    expose:
      - 28015
    command: rethinkdb --bind all -d /opt/app/db/ --no-update-check

